# Generated by Django 4.0.6 on 2022-07-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib', '0002_alter_book_options_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_lib.author'),
            preserve_default=False,
        ),
    ]
